#!/usr/bin/env python3
"""
Copyright (c)2015 Ulf Wostner <wostner@cyberprof.com> All rights reserved.
Do not post or distribute in any form.

This is a python script. Notice the very first line in this file.

It's starts with #! , 
see http://en.wikipedia.org/wiki/Shebang_%28Unix%29

You can run it two different ways:

$ python3 interactivescript

or make it executable first and then run it.

$ chmod u+x interactivescript
$ ./interactivescript

"""

prompt = "Are you here? [Yn]: "

while True:

    answer = input(prompt)
    answer = answer.strip()

    if not answer or answer[0] in ['Y', 'y']:
        affirmed = True
        break

    if answer[0] in ['N', 'n']:
        affirmed = False
        break

print('Affirmative?', affirmed)


