""" Template stuff for your webpage.

DO NOT EDIT THIS FILE.  It's complete already.

"""

pagedict = dict(title='TITLE_HERE', css='CSS_FILE_HERE', 
    content='CONTENT_HERE', footer='FOOTER_HERE')


PAGE_TEMPLATE = """
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <title>{title:}</title>
    <link TYPE="text/css" REL="stylesheet" HREF="{css:}">
</head>

<body>
  {content:}

   <p>
      <a href="http://validator.w3.org/check?uri=referer">
         <img 
            src="http://www.w3.org/Icons/valid-html401-blue" 
          alt="Valid HTML 4.01!" height="31" width="88" /></a>


<a href="http://jigsaw.w3.org/css-validator/check/referer">
    <img style="border:0;width:88px;height:31px"
        src="http://jigsaw.w3.org/css-validator/images/vcss-blue"
        alt="Valid CSS!" />
    </a>
</p>


  <hr />

 {footer:}

</body>

</html>
"""

